### ISSUE TITLE
Over speed in slave mode

### ISSUE THREAD

**Issue by woshigeshabiaaa** [DENSORobot/denso_robot_ros#19]
After i have changed my acceleration limits and velocity limits according to http://wiki.ros.org/denso_robot_ros/AcquireVelAcc
I am facing another problem that the robot stop frequently because of over speed issue.

The error message reads "J1 command speed limit over" (Not only J1 but every angle could happen), which means "The CP motion cannot execute with the specified speed because the speed command value of the 1st axis exceeds the limit value"

The command was generated by MoveIt, what could I do to avoid this problem? I don't wanna lose too much speed either.

**Comment by zeldamax** [comment]
For anyone wondering, the acceleration and velocity limits for Cobotta are defined in the following file named `joint_limits.yaml`:
```
joint_limits:
  joint_1:
    has_velocity_limits: true
    max_velocity: 0.40317105721069
    has_acceleration_limits: true
    max_acceleration: 2.0943951023932
  joint_2:
    has_velocity_limits: true
    max_velocity: 0.392175482923126
    has_acceleration_limits: true
    max_acceleration: 2.0943951023932
  joint_3:
    has_velocity_limits: true
    max_velocity: 0.725707902979242
    has_acceleration_limits: true
    max_acceleration: 3.49065850398866
  joint_4:
    has_velocity_limits: true
    max_velocity: 0.739146938219599
    has_acceleration_limits: true
    max_acceleration: 4.71238898038469
  joint_5:
    has_velocity_limits: true
    max_velocity: 0.739146938219599
    has_acceleration_limits: true
    max_acceleration: 4.71238898038469
  joint_6:
    has_velocity_limits: true
    max_velocity: 1.1093312725676
    has_acceleration_limits: true
    max_acceleration: 6.98131700797732
```
This file needs to be placed at `/opt/ros/melodic/share/denso_robot_moveit_config/config/$(robot_name)_config`
